### ISSUE TITLE
ERROR: Can't detect input format

### ISSUE THREAD

**Issue by moniekvanselst** [LUMC/HAMLET#3]
When running HAMLET with a smal sample annotate_vars gives a "ERROR: Can't detect input format". This could be caused by the fact that call_vars does not find any results.

The full error is in the attached file
[annotate_vars_ERROR.txt](https://github.com/LUMC/HAMLET/files/4737571/annotate_vars_ERROR.txt)

**Comment by Redmar-van-den-Berg** [comment]
Can you share a minimum fastq dataset (preferably) or set of inputs for annotate_vars that can be used to replicate this issue? Otherwise, it will be hard to pin down what goes wrong exactly.

**Comment by moniekvanselst** [comment]
Here is the sample that gave this error.
Note: this sample also gives the error is issue 2.

[NOMO1-RNAseq-1-16714.zip](https://github.com/LUMC/HAMLET/files/4757224/NOMO1-RNAseq-1-16714.zip)

**Comment by Redmar-van-den-Berg** [comment]
Looks like this issue was inadvertently solved by using a more recent version of the GMAP aligner. However, I did discover some other bugs with same input data, which are awaiting a response from the upstream projects.

1. https://github.com/bow/crimson/pull/12
2. https://github.com/ndaniel/fusioncatcher/issues/168
3. https://github.com/yhoogstrate/fuma/pull/44

**Comment by Redmar-van-den-Berg** [comment]
This has been fixed in the devel branch (See 9a46725d163)
