### ISSUE TITLE
Setting up config files

### ISSUE THREAD

**Issue by mathieuq** [LUMC/HAMLET#5]
HAMLET's readme references 4 modules: snv-indels, fusion, itd and expression. It is not clear how the config file must be set up in order to use one or more of the modules and the reference config files do not make it obvious. Would it be possible to provide a template config file for each of the modules that would make it straightforward for users to adapt for their needs, or provide a script that would take user-defined parameters (requested module, list of samples, path to fastq files,...) as arguments to create the config file?

**Comment by Redmar-van-den-Berg** [comment]
You can use [this](https://github.com/LUMC/HAMLET/blob/master/test/data/config/test-hamlet-frankenstein.config) configuration file as a starting point, just replace the paths to the reference files with your local copy.

The tests are organised by module, so if you want to run only the expression module you can check the command [here](https://github.com/LUMC/HAMLET/blob/master/test/test_expression.yml#L64).

Providing a template or script to generate the input files is tricky, since you have to explicitly specify the forward/reverse read files for each sample. At that point, you might as well just specify them into the config json file directly.

If you only want to run a specific part of HAMLET, you can specify the output files you want at the end of the command line, and then the pipeline will exit when all files have been generated. See this [test](https://github.com/LUMC/HAMLET/blob/master/test/test_snv_indels.yml#L131) for an example.
