### ISSUE TITLE
Test Errors

### ISSUE THREAD

**Issue by yanlina0205** [LUMC/HAMLET#9]
I have successfully installed the pipeline and singularity version 3.6.4, but when I test the pipeline with commands "pytest --tag functional"，there are many items fails. I have downloaded all required reference files and set correctly in the config files which are present in the test/data/config/ folder, but all of the test items are wrong. I don't know what's the problem？
It semms that when it run, it can't correctly read the config files, so that it can't get the reference files.
Or mayby I don't  correctly set the config files?
Waiting for your reply, thanks.

**Comment by Redmar-van-den-Berg** [comment]
Can you give more details about the errors you get when you try to run the tests? Do the tests you run with `pytest --kwd --tag sanity` all run successfully?

If you run the functional tests with `pytest --kwd --tag functional`, you can inspect the job folder (including the `log.out` and `log.err` files) to determine exactly what goes wrong. In general, the functional tests do not require any of the values from the configuration file, so that is unlikely to be the issue.

**Comment by yanlina0205** [comment]
Thanks for your reply.  I have displayed the details of the test commands in the attached files：
[pytest --tag sanity.txt](https://github.com/LUMC/HAMLET/files/5516015/pytest.--tag.sanity.txt)
[pytest --tag dry-run.txt](https://github.com/LUMC/HAMLET/files/5516016/pytest.--tag.dry-run.txt)
[pytest --tag functional.txt](https://github.com/LUMC/HAMLET/files/5516017/pytest.--tag.functional.txt)
And I have successfully run the align_flt3 by directly running the shell. But when I wanted to run the shell of detect_flt3, I found  that I don't have 'rose-dt'. By finding relevant information, I found the'rose-dt' is in docker.
I want to know whether the HAMLET only can be used in docker.
Later I installed the Docker Desktop, but I failed to set up the conda virtual environment. I'm not familiar with the docker, so maybe there are other problems with me.
Looking forward to your reply. Thanks again.

**Comment by Redmar-van-den-Berg** [comment]
HAMLET uses singularity to run docker containers, so you do not need to install docker directly. If the sanity checks pass, that means that you have the singularity command available, so everything should work.

I'm surprised that the dry-run tests from test_hamlet.yml and test_itd.yml fail, since those should work with the dummy files that are present by default. Can you run the tests for test_hamlet again manually and poste the `log.out` and `log.err` files in the test folder?

`pytest --kwd test/test_hamlet.yml --tag dry-run`

You can find the test folder from the output of the command after you run it. The bolded part will be different on your system:

start 'test-hamlet-dry-run-single' with command 'snakemake -n --snakefile Snakefile --configfile test/data/config/test-qc-single.config
' in '**/tmp/pytest_workflow_62uu1360/test-hamlet-dry-run-single**'. stdout: '/tmp/pytest_workflow_62uu1360/test-hamlet-dry-run-single/log.out'. stderr: '/tmp/pytest_workflow_62uu1360/test-hamlet-dry-run-single/log.err'.
'test-hamlet-dry-run-single' done.
start 'test-hamlet-dry-run-trio' with command 'snakemake -n --snakefile Snakefile --configfile test/data/config/test-qc-trio.config
' in '**/tmp/pytest_workflow_62uu1360/test-hamlet-dry-run-trio**'. stdout: '/tmp/pytest_workflow_62uu1360/test-hamlet-dry-run-trio/log.out'. stderr: '/tmp/pytest_workflow_62uu1360/test-hamlet-dry-run-trio/log.err'.
'test-hamlet-dry-run-trio' done.

**Comment by yanlina0205** [comment]
Thanks for your prompt reply. 
I download the HAMLET-devel again, and rerun the tests with pytest --kwd --tag sanity,dry-run,functional, the test items of sanity and dry-run all passed, while dry-run failed yesterday, but the 32 test items of functional still all failed. Corresponding log.out and log.err are shown below.
I also run the tests for test_hamlet again manually, it succeeded. The log.out and log.err are shown below.
The out and err file types are not supported, so I convert them to txt format.

[sanity_log.out.txt](https://github.com/LUMC/HAMLET/files/5521264/sanity_log.out.txt)
[dry-run_log.out.txt](https://github.com/LUMC/HAMLET/files/5521266/dry-run_log.out.txt)
[functional_log.err.txt](https://github.com/LUMC/HAMLET/files/5521269/functional_log.err.txt)
[test_hamlet_log.out.txt](https://github.com/LUMC/HAMLET/files/5521271/test_hamlet_log.out.txt)
[test_hamlet_log.err.txt](https://github.com/LUMC/HAMLET/files/5521272/test_hamlet_log.err.txt)

Looking forward to your reply. Thanks again.

**Comment by Redmar-van-den-Berg** [comment]
It looks like there were some network problems when downloading the docker containers that are needed to run the pipeline, for the functional tests:
```
FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://quay.io/biocontainers/cutadapt:1.14--py36_0: error pinging docker registry quay.io: Get https://quay.io/v2/: dial tcp: lookup quay.io: no such host
```

Can you try again today, I just tried to download the docker image and it appears to be working again. You can set your `SINGULARITY_CACHEDIR` if you want to store the images locally, so you are not dependent on an external service to pull them. See the [singularity documentation](https://sylabs.io/guides/3.3/user-guide/build_env.html#pull-folder) for details.

How did you download HAMLET exactly? I see that the test_hamlet failed because HAMLET is not a git repository. Can you download HAMLET again using `git clone git@github.com:LUMC/HAMLET.git`, that is currently the only supported way to run HAMLET. (HAMLET uses git to determine it's own version, which gets put in the final PDF report).

**Comment by yanlina0205** [comment]
I can't download HAMLET by using git clone git@github.com:LUMC/HAMLET.git, the error is shown below:
[ Cloning into 'HAMLET'...
Warning: Permanently added 'github.com,192.30.255.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. ]

So I download the zip as shown below 
![download](https://user-images.githubusercontent.com/71110585/98781390-33716900-2431-11eb-8873-5871cb9218de.png)

**Comment by Redmar-van-den-Berg** [comment]
In that case, you can use the following command:
`git clone https://github.com/LUMC/HAMLET.git`

**Comment by yanlina0205** [comment]
Thanks, I redownload HAMLET by using `git clone https://github.com/LUMC/HAMLET.git` and installed it successfully. But there are still some questions with `pytest --tag functional` and the log.err are shown below.
[log.err.txt](https://github.com/LUMC/HAMLET/files/5535925/log.err.txt)

**Comment by Redmar-van-den-Berg** [comment]
That looks like singularity itself is not installed properly, and not a problem with HAMLET.

`05b71b45568ce53c6c5821005933b1d7.simg: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found`

This issue sounds similar, otherwise please contact your system administrator.
https://github.com/hpcng/singularity/issues/5116

**Comment by yanlina0205** [comment]
OK, thank you so much for your guidance, I will try to solve next question.

**Comment by yanlina0205** [comment]
I showed my problems on the singularity, and HAMLET requires the latest version of singularity, `3.7.0-rc.2`.Details are shown here:
[https://github.com/hpcng/singularity/issues/5711](url)

**Comment by yanlina0205** [comment]
I manually tested HAMLET by using `snakemake -rp --snakefile Snakefile --configfile test/data/config/test-hamlet-frankenstein.config --use-singularity`, and most of the jobs are successful, while jobid  54 is wrong,the detail is shown below:
 Error in rule exon_cov_ref:
    jobid: 54
    output: .tmp.exon_cov_ref.bed
    shell:
        cat /xtdisk/wangqf_group/yanln/deps/data/ucsc_gencode.refFlat | grep -vP "chr.*alt	" | awk '{ split($10, starts, ","); split($11, ends, ","); for (i=1; i < length(starts); i++) { print $3"\t"starts[i]"\t"ends[i]"\t"gensub(/(\.[0-9]+)/,"", "g", $2)"\t"i"\t"$4 } }' | bedtools sort -faidx /xtdisk/wangqf_group/yanln/deps/data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.fai > .tmp.exon_cov_ref.bed
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

I searched the "bash strict mode" of snakemake and found the part of jobid 54(shown below),but several snakemake files are linked together so that I don't know how to modify the code. Do you know how to solve the problem? Thank you.

rule exon_cov_ref:
    input:
        ref_fai=settings["genome_fai"],
        ref_refflat=settings["annotation_refflat"],
    output:
        bed=temp(".tmp.exon_cov_ref.bed")
    singularity: containers["bedtools-2.27-grep-2.14-gawk-5.0-click-7-python-3.7"]
    shell:
        "cat {input.ref_refflat}"
        " | grep -vP \"chr.*alt\t\""
        " | awk '{{ split($10, starts, \",\"); split($11, ends, \",\"); for (i=1; i < length(starts); i++) {{ print $3\"\\t\"starts[i]\"\\t\"ends[i]\"\\t\"gensub(/(\.[0-9]+)/,\"\", \"g\", $2)\"\\t\"i\"\\t\"$4 }} }}'"
        " | bedtools sort -faidx {input.ref_fai}"
        " > {output.bed}"

**Comment by Redmar-van-den-Berg** [comment]
That is probably because the singularity container doesn't have access to `/xtdisk`. You can run the following command to give the singularity container access to `/xtdisk`.

```bash
snakemake -rp \
--snakefile Snakefile \
--configfile test/data/config/test-hamlet-frankenstein.config \
--use-singularity \
--singularity-args ' --containall --bind /xtdisk'
```
